#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: redraiment/extension-ci-tools/.github/workflows/_extension_distribution.yml@735a214d5ef418bff17edef7fcb8b45b26dc2d25
    with:
      duckdb_version: v1.3.2
      ci_tools_version: "735a214d5ef418bff17edef7fcb8b45b26dc2d25"
      override_ci_tools_repository: "redraiment/extension-ci-tools"
      extension_name: rusty_sheet
      extra_toolchains: rust;python3
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;linux_amd64_musl'
